#!/usr/bin/env bash

# Get directory where the script is located
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Modules
module load miniconda/23.5.2

# Init
mkdir -p log

# Get jobs
JOB_COUNT=$1

shift

# Run
snakemake -s ${SOURCE_DIR}/align_all.smk -j ${JOB_COUNT} -p --ri --use-conda --conda-prefix=${SOURCE_DIR}/conda -w 60 "$@"
