#!/usr/bin/env bash

# DO NOT USE THIS FOR YOUR REGULAR ALIGNMENTS !!!!!!!

########### If you're curious what this is ###################################################################

# Hello! This is just a copy of runsnake. This will sleep for 48 hours before actually running anything.
# I am out on vacation but need to run some alignments without taking up a lot of cluster resources (i already am using up a lot).
# so just delaying submission while my current jobs finish!
# Please use the plain old regular runsnake for your alignments!
# Sorry for the inconvenience! :)

##############################################################################################################



# Get directory where the script is located
SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

SOURCE_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Modules
module load miniconda/23.5.2

# Init
mkdir -p log

# Get jobs
JOB_COUNT=$1

shift

# Run
sleep 172800 && snakemake -s ${SOURCE_DIR}/align_all.smk \
	-j ${JOB_COUNT} \
	--jobname "{rulename}.{jobid}" \
	--drmaa " -V -cwd -j y -o ./log -e ./log -l h_rt={resources.hrs}:00:00 -l mfree={resources.mem}G -pe serial {threads} -w n -S /bin/bash" \
	-w 30 "$@" \
	--use-singularity  \
	--singularity-args "--bind /net:/net"  \
	--restart-times 3 \
	--printshellcmds \
	--keep-going \
	--ri
